vector_store:
  use_remote: true
  remote_host: "aipg.dudelabz.com"
  remote_port: 8000
  collection_name: "vendor_emails"

neo4j:
  uri: bolt://aipg.dudelabz.com:7687
  user: neo4j
  password: ${NEO4J_PASSWORD}

bedrock:
  region: eu-west-1
  embedding_model: amazon.titan-embed-text-v2:0
  classification_model: anthropic.claude-3-haiku-20240307-v1:0

rag:
  answer_model: "anthropic.claude-3-sonnet-20240229-v1:0"
  max_tokens: 700
  temperature: 0.0

debug:
  enabled: True
  verbose_logging: True
  evaluation:
    enabled: True
    top_k: 15
    show_confidence_score: True
    queries:
      - "look for anything about price updates or changes"
      - "look for anything about Webinar invites"
      - "look for anything about Hashicorp product updates"
      - "look for any campaigns or sales related deals"
      - "fetch All event and webinar announcements received in the last 3 weeks"
      - "look for any terraform related emails"