version: '3'

services:
  vendor-updater:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ${EMAIL_FOLDER:-./misc/tst_emls}:/data/emails
    environment:
      - EMAIL_PASS=${EMAIL_PASS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-west-1
    restart: unless-stopped
    # For cron-like scheduling, uncomment and adjust as needed:
    # command: sh -c "while true; do python main.py; sleep 7200; done"  # Run every 2 hours