version: '3.8'

services:
  ingestion:
    build:
      context: ../..
      dockerfile: Docker/ingestion/Dockerfile
    environment:
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - IMAP_SERVER=${IMAP_SERVER}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
    volumes:
      - ../../data:/app/data
      - ../../logs:/app/logs
      - ../../config:/app/config
    restart: unless-stopped
    command: ["python", "main.py", "--local", "--folder", "data/raw_emails"]