version: '3.8'

services:
  terasky-rag:
    build:
      context: ..
      dockerfile: docker/rag-api/Dockerfile
    container_name: terasky-rag-api
    ports:
      - "8000:8000"
    environment:
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
      - CHROMA_HOST=${CHROMA_HOST:-aipg.dudelabz.com}
      - CHROMA_PORT=${CHROMA_PORT:-8000}
    volumes:
      - ../config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3