email:
  imap_server: imap.gmail.com
  email_address: davidplayground333@gmail.com
  password: wbqq qntg rxys fwid  # Secure via .env or secrets manager in prod
  folder: INBOX
  mark_as_read: true
  fetch_interval_minutes: 120

classification:
  labels:
    marketing:
      - promo
      - event
      - webinar
      - announcement
    security:
      - vulnerability
      - patch
      - maintenance
    technical:
      - support
      - product update
      - whitepaper
  multi_label: true

data_processing:
  language_support:
    - en
    - he
  chunk_size_tokens: 512
  chunk_overlap: 20
  save_intermediate_artifacts: true

embedding:
  provider: amazon
  model: anthropic.claude-3-haiku-20240307-v1:0

indexing:
  vector_db: chromadb
  hybrid_search: true
  manifest_path: ./index_manifest.jsonl

debug:
  enabled: true
  verbose_logging: true
  save_all_artifacts: true
  evaluation:
    enabled: true
    top_k: 3
    show_confidence_score: true